version: '3.8'

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    environment:
      DATABASE_URL: ${DATABASE_URL}
      REDIS_URL: redis://redis:6379
      REDIS_HOST: redis
      REDIS_PORT: 6379
      SESSION_SECRET: ${SESSION_SECRET:-dev-secret-key}
      RESEND_API_KEY: ${RESEND_API_KEY}
      CONTACT_EMAIL_TO: ${CONTACT_EMAIL_TO}
    ports:
      - "8000:8000"
    depends_on:
      redis:
        condition: service_healthy
    volumes:
      - ./backend:/app/backend  # Hot reload for development
    command: uvicorn backend.main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile.dev  # ← New dev Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - backend
    volumes:
      - ./frontend/src:/app/src  # Hot reload
      - ./frontend/vite.config.ts:/app/vite.config.ts
    environment:
      - NODE_ENV=development